# config/routes/security.yaml
auth_register:
    path: /auth/register
    controller: App\Module\Auth\Controller\RegistrationController::register
    methods: [POST]

auth_login:
    path: /auth/login
    controller: App\Module\Auth\Controller\SecurityController::login
    methods: [POST]

auth_logout:
    path: /auth/logout
    controller: App\Module\Auth\Controller\SecurityController::logout
    methods: [POST]
