framework:
    secret: '%env(APP_SECRET)%'
    
    session:
        handler_id: null
        save_path: '/tmp/sessions'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    csrf_protection: true

    # Estos encabezados son los que env√≠a Vercel
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']