auth_controllers:
    resource:
        path: ../src/Module/Auth/Controller/
        namespace: App\Module\Auth\Controller
    type: attribute

movie_controllers:
    resource: ../src/Module/Movie/Controller/
    type: attribute

group_controllers:
    resource: ../src/Module/Group/Controller/
    type: attribute