name: Tareas Diarias ClubCine

on:
  schedule:
    # Se ejecuta a las 00:00 UTC todos los días
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde el botón de GitHub

jobs:
  close-movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, mysql
          coverage: none

      - name: Instalar dependencias
        # Usamos --no-dev para evitar el error del DebugBundle que viste en local
        run: composer install --no-dev --optimize-autoloader

      - name: Ejecutar comando de cierre de películas
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_ENV: prod
        run: php bin/console app:group:close-expired