name: Tareas Diarias ClubCine

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

# Definimos las variables aquí arriba para que afecten a TODO el proceso
env:
  APP_ENV: prod
  APP_DEBUG: 0

jobs:
  close-movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, mysql
          coverage: none

      - name: Instalar dependencias
        # Eliminamos temporalmente los scripts post-install para evitar que falle si la caché se pone terca
        run: composer install --no-dev --optimize-autoloader --no-scripts
        working-directory: club-cine

      - name: Ejecutar comando de cierre de películas
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        # Añadimos --no-debug para estar 100% seguros
        run: php bin/console app:group:close-expired --no-debug -vvv
        working-directory: club-cine