name: Tareas Diarias ClubCine

on:
  schedule:
    # Se ejecuta a las 00:00 UTC todos los días
    - cron: '0 0 * * *'
  workflow_dispatch: # Activa el botón para ejecutarlo manualmente

jobs:
  close-movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, mysql
          coverage: none

      - name: Instalar dependencias
        env:
          APP_ENV: prod # Forzamos entorno prod para que ignore el DebugBundle
        run: composer install --no-dev --optimize-autoloader
        working-directory: club-cine

      - name: Ejecutar comando de cierre de películas
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_ENV: prod
          APP_DEBUG: 0
        # El flag -vvv nos mostrará detalles si hay errores de conexión
        run: php bin/console app:group:close-expired -vvv
        working-directory: club-cine