name: Tareas Diarias ClubCine

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  close-movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, mysql
          coverage: none

      - name: Instalar dependencias
        # Entramos en la carpeta club-cine para instalar
        run: composer install --no-dev --optimize-autoloader
        working-directory: club-cine

      - name: Ejecutar comando de cierre de películas
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_ENV: prod
        # Entramos en la carpeta club-cine para ejecutar el comando
        run: php bin/console app:group:close-expired
        working-directory: club-cine